import unittest


class TestPostProcessing(unittest.TestCase):
    def test_init(self):
        self.fail()

    def test_process(self):
        self.fail()

    def test_fix_issues(self):
        self.fail()


def test_construct_regex_patterns_from_predictions(self):  # FIXME is that ok? --> self in outer class method
    self.fail()

if __name__ == '__main__':
    unittest.main()